Fix: Py3: don't use str.decode()
`str.decode('utf-8')` is obsolete, and `str.decode` has been removed
since Python 3 makes everything Unicode by default. This commit avoids
receiving the following error for the TLDR adapter:
`AttributeError: 'str' object has no attribute 'decode'`